services:
  kkgo:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_URL=host=localhost port=5432 user=postgres password=postgres dbname=ktaxes sslmode=disable
      - ADMIN_USERNAME=adminTax
      - ADMIN_PASSWORD=admin!
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ktaxes
    ports:
      - "5432:5432"
