// Code generated by mockery v2.38.0. DO NOT EDIT.

package deductions

import (
	decimal "github.com/shopspring/decimal"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// GetMaximumDeduction provides a mock function with given fields: allowanceType
func (_m *MockRepository) GetMaximumDeduction(allowanceType string) (TblMaximumDeduction, error) {
	ret := _m.Called(allowanceType)

	if len(ret) == 0 {
		panic("no return value specified for GetMaximumDeduction")
	}

	var r0 TblMaximumDeduction
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (TblMaximumDeduction, error)); ok {
		return rf(allowanceType)
	}
	if rf, ok := ret.Get(0).(func(string) TblMaximumDeduction); ok {
		r0 = rf(allowanceType)
	} else {
		r0 = ret.Get(0).(TblMaximumDeduction)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(allowanceType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertMaximumDeduction provides a mock function with given fields: allowanceType, amount
func (_m *MockRepository) UpsertMaximumDeduction(allowanceType string, amount decimal.Decimal) error {
	ret := _m.Called(allowanceType, amount)

	if len(ret) == 0 {
		panic("no return value specified for UpsertMaximumDeduction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, decimal.Decimal) error); ok {
		r0 = rf(allowanceType, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
