// Code generated by mockery v2.38.0. DO NOT EDIT.

package uploadcsv

import mock "github.com/stretchr/testify/mock"

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// GetMaximumDeduction provides a mock function with given fields:
func (_m *MockRepository) GetMaximumDeduction() ([]TblMaximumDeduction, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMaximumDeduction")
	}

	var r0 []TblMaximumDeduction
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]TblMaximumDeduction, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []TblMaximumDeduction); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]TblMaximumDeduction)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
